name: Compile

on:
  push:
    branches:
      - "master"
    paths:
      - "**/*.c"
      - "**/*.h"
      - "**/*.cpp"
      - "**/*.hpp"
      - "config"
      - "!.clang-format"
      - "!LICENSE"
      - "!.gitignore"
      - "!README.md"
  workflow_dispatch:


defaults:
  run:
    shell: bash


permissions:
  packages: read
  actions: read
  contents: read


jobs:
  compile:
    name: Compile ${{ matrix.nginx_version }} (${{ matrix.gcc_image }})
    strategy:
      fail-fast: false
      matrix:
        gcc_image: ["gcc:10.2", "gcc:11", "gcc:12.4", "gcc:13.3", "gcc:14.2"]
        nginx_version: ["1.21.0", "1.21.4", "1.22.1", "1.23.4", "1.24.0", "1.25.4", "1.25.5", "1.26.2", "1.27.4"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.gcc_image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Compile
        run: |
          export WORKING_DIR="$(pwd)"
          wget --no-verbose -O "nginx.tar.gz" "https://nginx.org/download/nginx-${{ matrix.nginx_version }}.tar.gz"
          tar -xf nginx.tar.gz
          cd nginx-${{ matrix.nginx_version }}
          chmod +x configure
          ./configure --add-module="$WORKING_DIR" --with-stream --without-http
          make