name: Compile

on:
  push:
    branches:
      - "master"
    paths:
      - "**/*.c"
      - "**/*.h"
      - "**/*.cpp"
      - "**/*.hpp"
      - "config"
      - "!.clang-format"
      - "!LICENSE"
      - "!.gitignore"
      - "!README.md"
  workflow_dispatch:


defaults:
  run:
    shell: bash


jobs:
  compile:
    name: Compile ${{ matrix.nginx_version }} (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04", "ubuntu-24.04", "ubuntu-22.04-arm", "ubuntu-24.04-arm"]
        nginx_version: ["1.22.1", "1.23.4", "1.24.0", "1.25.4", "1.25.5", "1.26.2", "1.27.4", "CrimsonEdgeHope"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          java-package: "jre"
      
      - name: Compile Nginx
        id: compile
        run: |
          export COSMETIC_DIR=$(pwd)
          echo "cosmetic_dir=$COSMETIC_DIR" >> $GITHUB_OUTPUT
          
          if [[ "${{ matrix.nginx_version }}" == "CrimsonEdgeHope" ]]; then
            git clone https://github.com/CrimsonEdgeHope/nginx.git nginx-${{ matrix.nginx_version }}
            cd nginx-${{ matrix.nginx_version }}
            cp auto/configure .
          else
            wget --no-verbose -O "nginx.tar.gz" "https://nginx.org/download/nginx-${{ matrix.nginx_version }}.tar.gz"
            tar -xf nginx.tar.gz
            cd nginx-${{ matrix.nginx_version }}
          fi
          
          chmod +x configure
          ./configure --add-module=$COSMETIC_DIR --with-stream --with-debug --without-http --with-pcre --with-ld-opt="-lstdc++"
          make
      
      - name: Setup mcping amd64
        if: ${{ !endsWith(matrix.os, 'arm') }}
        working-directory: ${{ steps.compile.outputs.cosmetic_dir }}
        run: |
          wget --no-verbose -O "mcping" "https://github.com/NetherRealmSpigot/mcping/releases/download/v0.0.1/mcping-0.0.1-linux-amd64"
          chmod +x ./mcping
      
      - name: Setup mcping arm64
        if: ${{ endsWith(matrix.os, 'arm') }}
        working-directory: ${{ steps.compile.outputs.cosmetic_dir }}
        run: |
          wget --no-verbose -O "mcping" "https://github.com/NetherRealmSpigot/mcping/releases/download/v0.0.1/mcping-0.0.1-linux-arm64"
          chmod +x ./mcping
      
      - name: Setup PandaSpigot
        working-directory: ${{ steps.compile.outputs.cosmetic_dir }}
        run: |
          mkdir -p spigot
          cd spigot

          export SPIGOT_JAR="spigot.jar"
          
          curl -o $SPIGOT_JAR -fsSL https://downloads.hpfxd.com/v2/projects/pandaspigot/versions/1.8.8/builds/latest/downloads/paperclip
          
          mkdir -p plugins
          curl -o plugins/viaversion.jar -fsSL https://github.com/ViaVersion/ViaVersion/releases/download/5.2.1/ViaVersion-5.2.1.jar

          mkdir -p plugins/ViaVersion
          cat << EOF > plugins/ViaVersion/config.yml
          check-for-updates: false
          send-supported-versions: true
          block-versions: []
          block-protocols: []
          block-disconnect-msg: You are using an unsupported Minecraft version!
          reload-disconnect-msg: Server reload, please rejoin!
          suppress-conversion-warnings: true
          max-pps: 800
          max-pps-kick-msg: You are sending too many packets!
          tracking-period: 6
          tracking-warning-pps: 120
          tracking-max-warnings: 4
          tracking-max-kick-msg: You are sending too many packets, :(
          register-userconnections-on-join: true
          hologram-patch: false
          hologram-y: -0.96
          piston-animation-patch: false
          chat-nbt-fix: true
          quick-move-action-fix: false
          team-colour-fix: true
          disable-1_13-auto-complete: false
          1_13-tab-complete-delay: 10
          fix-low-snow-collision: true
          fix-infested-block-breaking: true
          truncate-1_14-books: true
          change-1_9-hitbox: false
          change-1_14-hitbox: false
          fix-non-full-blocklight: true
          fix-1_14-health-nan: true
          use-1_15-instant-respawn: false
          serverside-blockconnections: true
          blockconnection-method: packet
          reduce-blockstorage-memory: false
          flowerstem-when-block-above: false
          vine-climb-fix: false
          ignore-long-1_16-channel-names: true
          forced-use-1_17-resource-pack: false
          resource-pack-1_17-prompt: ''
          cache-1_17-light: true
          armor-toggle-fix: true
          map-1_16-world-names:
            overworld: minecraft:overworld
            nether: minecraft:the_nether
            end: minecraft:the_end
          translate-ocelot-to-cat: false
          enforce-secure-chat: false
          handle-invalid-item-count: false
          hide-scoreboard-numbers: false
          fix-1_21-placement-rotation: true
          prevent-collision: true
          auto-team: true
          suppress-metadata-errors: true
          shield-blocking: false
          no-delay-shield-blocking: false
          show-shield-when-sword-in-hand: false
          simulate-pt: true
          nms-player-ticking: true
          bossbar-patch: true
          bossbar-anti-flicker: false
          use-new-effect-indicator: true
          use-new-deathmessages: true
          item-cache: true
          replace-pistons: false
          replacement-piston-id: 0
          chunk-border-fix: false
          left-handed-handling: false
          cancel-block-sounds: true
          sword-blocking-via-consumable: true
          EOF

          cat << EOF > bukkit.yml
          settings:
            allow-end: false
            warn-on-overload: true
            permissions-file: permissions.yml
            update-folder: update
            plugin-profiling: false
            connection-throttle: 4000
            query-plugins: false
            deprecated-verbose: default
            shutdown-message: Server closed
          spawn-limits:
            monsters: 70
            animals: 15
            water-animals: 5
            ambient: 15
          chunk-gc:
            period-in-ticks: 600
            load-threshold: 0
          ticks-per:
            animal-spawns: 400
            monster-spawns: 1
            autosave: 6000
          aliases: now-in-commands.yml
          database:
            username: bukkit
            isolation: SERIALIZABLE
            driver: org.sqlite.JDBC
            password: walrus
            url: jdbc:sqlite:{DIR}{NAME}.db
          EOF

          cat << EOF > commands.yml
          command-block-overrides: []
          aliases:
            icanhasbukkit:
            - version $1-
          EOF

          cat << EOF > eula.txt
          eula=true
          EOF

          cat << EOF > pandaspigot.yml
          trackPluginScoreboards: false
          proxyOnlineMode: true
          maxBookPageSize: 2560
          maxBookTotalSizeMultiplier: 0.98
          packetLimiter:
            kickMessage: "&cSent too many packets."
            limits:
              all:
                interval: 7.0
                maxPacketRate: 500.0
          logPlayerIpAddresses: true
          worlds:
            default:
              timeUpdateFrequency: 100
              smoothTeleportation: false
              disablePlayerData: true
              disableChunkSaving: true
              disableEntityAi: true
              randomArrowTrajectory: true
              knockback:
                friction: 2.0
                horizontal: 0.4
                vertical: 0.4
                verticalLimit: 0.4000000059604645
                extraHorizontal: 0.5
                extraVertical: 0.1
              optimizeTntMovement: false
              optimizeLiquidExplosions: true
              optimizeArmorStandMovement: false
              randomArrowDamage: true
          EOF

          cat << EOF > paper.yml
          config-version: 9
          data-value-allowed-items: []
          settings:
            baby-zombie-movement-speed: 0.5
            limit-player-interactions: true
          effect-modifiers:
            strength: 1.3
            weakness: -0.5
          stackable-buckets:
            lava: false
            water: false
            milk: false
          warnWhenSettingExcessiveVelocity: true
          world-settings:
            default:
              verbose: true
              keep-spawn-loaded: true
              generator-settings:
                canyon: true
                caves: true
                dungeon: true
                fortress: true
                mineshaft: true
                monument: true
                stronghold: true
                temple: true
                village: true
                flat-bedrock: false
              allow-block-location-tab-completion: true
              disable-thunder: false
              disable-ice-and-snow: false
              tick-next-tick-list-cap: 10000
              tick-next-tick-list-cap-ignores-redstone: false
              falling-blocks-collide-with-signs: false
              disable-mood-sounds: false
              use-async-lighting: false
              portal-search-radius: 128
              player-blocking-damage-multiplier: 0.5
              remove-invalid-mob-spawner-tile-entities: true
              optimize-explosions: false
              mob-spawner-tick-rate: 1
              cache-chunk-maps: false
              tnt-explosion-volume: 4.0
              disable-teleportation-suffocation-check: false
              squid-spawn-height:
                minimum: 45.0
                maximum: 63.0
              max-growth-height:
                cactus: 3
                reeds: 3
              fishing-time-range:
                MinimumTicks: 100
                MaximumTicks: 900
              player-exhaustion:
                block-break: 0.02500000037252903
                swimming: 0.014999999664723873
              despawn-ranges:
                soft: 32
                hard: 128
              falling-block-height-nerf: 0
              remove-unloaded:
                enderpearls: true
                tnt-entities: true
                falling-blocks: true
              game-mechanics:
                boats-drop-boats: false
                disable-player-crits: false
                disable-chest-cat-detection: false
                disable-end-credits: false
              nether-ceiling-void-damage: false
              load-chunks:
                enderpearls: false
                tnt-entities: false
                falling-blocks: false
              fast-drain:
                lava: false
                water: false
              lava-flow-speed:
                normal: 30
                nether: 10
              disable-explosion-knockback: false
              water-over-lava-flow-speed: 5
              fix-cannons: false
              tnt-entity-height-nerf: 0
              use-hopper-check: false
              all-chunks-are-slime-chunks: false
              allow-undead-horse-leashing: false
              container-update-tick-rate: 1
          EOF

          cat << EOF > spigot.yml
          config-version: 8
          settings:
            debug: false
            late-bind: false
            sample-count: 0
            player-shuffle: 0
            filter-creative-items: true
            user-cache-size: 1000
            save-user-cache-on-stop-only: false
            int-cache-limit: 1024
            bungeecord: false
            moved-wrongly-threshold: 0.0625
            moved-too-quickly-threshold: 100.0
            timeout-time: 60
            restart-on-crash: false
            restart-script: ./start.sh
            netty-threads: 4
            attribute:
              maxHealth:
                max: 2048.0
              movementSpeed:
                max: 2048.0
              attackDamage:
                max: 2048.0
          messages:
            whitelist: You are not whitelisted on this server!
            unknown-command: Unknown command. Type "/help" for help.
            server-full: The server is full!
            outdated-client: Outdated client! Please use {0}
            outdated-server: Outdated server! I'm still on {0}
            restart: Server is restarting
          stats:
            disable-saving: true
            forced-stats: {}
          commands:
            tab-complete: 0
            spam-exclusions:
            - /skill
            silent-commandblock-console: false
            replace-commands:
            - setblock
            - summon
            - testforblock
            - tellraw
            log: true
          timings:
            enabled: true
            verbose: true
            server-name-privacy: false
            hidden-config-entries:
            - database
            - settings.bungeecord-addresses
            history-interval: 300
            history-length: 3600
          world-settings:
            default:
              verbose: true
              chunks-per-tick: 650
              clear-tick-list: false
              merge-radius:
                exp: 3.0
                item: 2.5
              anti-xray:
                enabled: true
                engine-mode: 1
                hide-blocks:
                - 14
                - 15
                - 16
                - 21
                - 48
                - 49
                - 54
                - 56
                - 73
                - 74
                - 82
                - 129
                - 130
                replace-blocks:
                - 1
                - 5
              mob-spawn-range: 4
              nerf-spawner-mobs: false
              growth:
                cactus-modifier: 100
                cane-modifier: 100
                melon-modifier: 100
                mushroom-modifier: 100
                pumpkin-modifier: 100
                sapling-modifier: 100
                wheat-modifier: 100
                netherwart-modifier: 100
              entity-activation-range:
                animals: 32
                monsters: 32
                misc: 16
              entity-tracking-range:
                players: 48
                animals: 48
                monsters: 48
                misc: 32
                other: 64
              ticks-per:
                hopper-transfer: 8
                hopper-check: 8
              hopper-amount: 1
              random-light-updates: false
              save-structure-info: true
              max-bulk-chunks: 10
              max-entity-collisions: 8
              dragon-death-sound-radius: 0
              seed-village: 10387312
              seed-feature: 14357617
              hunger:
                walk-exhaustion: 0.2
                sprint-exhaustion: 0.8
                combat-exhaustion: 0.3
                regen-exhaustion: 3.0
              max-tnt-per-tick: 100
              item-despawn-rate: 6000
              arrow-despawn-rate: 1200
              enable-zombie-pigmen-portal-spawns: true
              wither-spawn-sound-radius: 0
              view-distance: 10
              hanging-tick-frequency: 100
              zombie-aggressive-towards-villager: true
          EOF

          cat << EOF > server.properties
          allow-flight=false
          allow-nether=false
          announce-player-achievements=true
          difficulty=1
          enable-command-block=false
          enable-query=false
          enable-rcon=false
          force-gamemode=false
          gamemode=0
          generate-structures=false
          generator-settings=
          hardcore=false
          level-name=world
          level-seed=
          level-type=FLAT
          max-build-height=256
          max-players=2
          max-world-size=29999984
          motd=A Minecraft Server
          network-compression-threshold=256
          online-mode=false
          op-permission-level=4
          player-idle-timeout=0
          pvp=true
          resource-pack=
          resource-pack-hash=
          server-ip=127.0.0.1
          server-port=25567
          snooper-enabled=false
          spawn-animals=false
          spawn-monsters=false
          spawn-npcs=false
          use-native-transport=true
          view-distance=4
          white-list=false
          EOF

          nohup java -jar $SPIGOT_JAR nogui 2>&1 &
          sleep 5
        continue-on-error: false
      
      - name: Setup Nginx
        working-directory: ${{ steps.compile.outputs.cosmetic_dir }}
        run: |
          cd nginx-${{ matrix.nginx_version }}
          
          mkdir -p logs
          touch logs/access.log
          touch logs/error.log
          
          cat << EOF > conf/nginx.conf
          master_process  off;
          worker_processes  auto;

          error_log   logs/error.log  debug;

          events {
              worker_connections  1024;
          }

          stream {
              resolver 1.1.1.1 8.8.8.8 ipv6=off valid=60s;

              minecraft_server_hostname  127.0.0.1  test;
              minecraft_server_hostname  localhost  test;
              
              minecraft_server_hostname_replace_on_ping  on;
              minecraft_server_hostname_disconnect_on_nomatch  off;
              
              server {
                  listen 25565;
                  proxy_pass  127.0.0.1:25567;
                  minecraft_server_forward on;
              }
          }
          EOF
          
          chmod +x objs/nginx
          objs/nginx -V
          objs/nginx -p $(pwd) -t
          objs/nginx -p $(pwd) -g "daemon on;"
      
      - name: Run pinging
        working-directory: ${{ steps.compile.outputs.cosmetic_dir }}
        run: |
          protocol_numbers=(
            763 764 765 766 767 768 769
            755 756 757 758 759 760 761 762
            573 575 578 735 736 751 753 754
            393 401 404 477 480 485 490 498
            210 315 316 335 338 340
            47 107 108 109 110
            3 4 5
          )
          
          export PING_QUERY_COUNT=60
          export PING_QUERY_ROUNDWAIT=2
          
          declare -i max_query_count=$PING_QUERY_COUNT
          declare -i i_count=0
          
          for protocol_i in "${protocol_numbers[@]}"; do
            i_count=0
            echo $protocol_i
            while [ $i_count -le $max_query_count ]; do
              i_count+=1
              if ./mcping --host 127.0.0.1 --protocol $protocol_i; then
                break;
              elif [[ $i_count -eq $max_query_count ]]; then
                echo "PING FAILURE."
                exit 1;
              fi
              echo "Retrying"
              sleep $PING_QUERY_ROUNDWAIT
            done
          done
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: ${{ github.run_id }}-${{ matrix.os }}-nginx-${{ matrix.nginx_version }}
          path: |
            ${{ steps.compile.outputs.cosmetic_dir }}/nginx-${{ matrix.nginx_version }}
            ${{ steps.compile.outputs.cosmetic_dir }}/spigot/crash-reports
            ${{ steps.compile.outputs.cosmetic_dir }}/spigot/logs
          retention-days: 1
          overwrite: true
        continue-on-error: true